/* ============================================================
   WordLab · 단어 데이터  (수능 기본 어휘 1단계 · 어원·구조 분석 200)
   스키마: { w 단어, pron 발음, pos 품사, mean 뜻, struct 어원·구조, ex 예문, exKo 해석 }
   - 10단어 = 1 Day (Day 1 = 1~10 ... Day 20 = 191~200)
   - 새 단어장은 LEVELS 에 추가하고 ACTIVE_LEVEL 만 바꾸면 됩니다.
   ============================================================ */
const LEVELS = {
  S1: {
    code: "S1",
    label: "수능 기본 어휘 1단계 · 어원·구조 분석 200",
    perDay: 10,
    words: [
      {w:"abandon",pron:"/əˈbændən/",pos:"v",mean:"버리다, 포기하다",struct:"a-(~로) + bandon(통제) → 통제 밖에 두다 → 버리다",ex:"They had to abandon the sinking ship.",exKo:"그들은 가라앉는 배를 버려야 했다."},
      {w:"ability",pron:"/əˈbɪləti/",pos:"n",mean:"능력",struct:"abil(=able 할 수 있는) + -ity(명사) → 할 수 있음",ex:"She has the ability to lead.",exKo:"그녀는 이끄는 능력이 있다."},
      {w:"absorb",pron:"/əbˈzɔːrb/",pos:"v",mean:"흡수하다",struct:"ab-(~로부터) + sorb(빨아들이다) → 빨아들이다",ex:"Plants absorb water through roots.",exKo:"식물은 뿌리로 물을 흡수한다."},
      {w:"abstract",pron:"/ˈæbstrækt/",pos:"adj",mean:"추상적인",struct:"abs-(분리) + tract(끌다) → 끌어내어 떼어 놓은 → 추상적",ex:"Love is an abstract idea.",exKo:"사랑은 추상적인 개념이다."},
      {w:"accept",pron:"/əkˈsept/",pos:"v",mean:"받아들이다",struct:"ac-(~쪽으로) + cept(잡다) → 잡아 들이다",ex:"I accept your apology.",exKo:"나는 너의 사과를 받아들인다."},
      {w:"access",pron:"/ˈækses/",pos:"n/v",mean:"접근(하다)",struct:"ac-(~로) + cess(가다) → ~로 감 → 접근",ex:"Students have access to the library.",exKo:"학생들은 도서관을 이용할 수 있다."},
      {w:"accomplish",pron:"/əˈkɑːmplɪʃ/",pos:"v",mean:"성취하다",struct:"ac-(강조) + compl(채우다) → 다 채우다 → 완수",ex:"She accomplished her goal.",exKo:"그녀는 목표를 성취했다."},
      {w:"accurate",pron:"/ˈækjərət/",pos:"adj",mean:"정확한",struct:"ac-(강조) + cur(주의) + -ate → 주의를 기울인 → 정확",ex:"The clock is accurate.",exKo:"그 시계는 정확하다."},
      {w:"achieve",pron:"/əˈtʃiːv/",pos:"v",mean:"이루다, 달성하다",struct:"a-(~로) + chieve(=chief 끝, 머리) → 끝에 다다르다",ex:"He achieved great success.",exKo:"그는 큰 성공을 이루었다."},
      {w:"acquire",pron:"/əˈkwaɪər/",pos:"v",mean:"습득하다, 얻다",struct:"ac-(~로) + quire(구하다) → 구해서 갖다",ex:"Babies acquire language fast.",exKo:"아기는 언어를 빨리 습득한다."},

      {w:"adapt",pron:"/əˈdæpt/",pos:"v",mean:"적응하다, 조정하다",struct:"ad-(~에) + apt(알맞은) → ~에 알맞게 맞추다",ex:"Animals adapt to their environment.",exKo:"동물은 환경에 적응한다."},
      {w:"adequate",pron:"/ˈædɪkwət/",pos:"adj",mean:"충분한, 적절한",struct:"ad-(~에) + equ(같은) + -ate → ~에 알맞게 같은 → 적절",ex:"The room is adequate for two.",exKo:"그 방은 두 명에게 충분하다."},
      {w:"adjust",pron:"/əˈdʒʌst/",pos:"v",mean:"조정하다, 맞추다",struct:"ad-(~에) + just(올바른) → 올바르게 맞추다",ex:"Adjust the volume, please.",exKo:"소리를 조절해 주세요."},
      {w:"admire",pron:"/ədˈmaɪər/",pos:"v",mean:"존경하다, 감탄하다",struct:"ad-(~에) + mire(놀라다, 보다) → 보고 놀라다",ex:"I admire her courage.",exKo:"나는 그녀의 용기에 감탄한다."},
      {w:"admit",pron:"/ədˈmɪt/",pos:"v",mean:"인정하다, 들이다",struct:"ad-(~로) + mit(보내다) → 안으로 보내다 → 받아들이다",ex:"He admitted his mistake.",exKo:"그는 자신의 실수를 인정했다."},
      {w:"adopt",pron:"/əˈdɑːpt/",pos:"v",mean:"채택하다, 입양하다",struct:"ad-(~로) + opt(고르다) → 골라서 받아들이다",ex:"They adopted a new rule.",exKo:"그들은 새 규칙을 채택했다."},
      {w:"advance",pron:"/ədˈvæns/",pos:"v/n",mean:"전진(하다), 발전",struct:"ad-(앞으로) + vance(가다) → 앞으로 가다",ex:"Science continues to advance.",exKo:"과학은 계속 발전한다."},
      {w:"advantage",pron:"/ədˈvæntɪdʒ/",pos:"n",mean:"이점, 장점",struct:"advant(앞선) + -age → 앞선 위치 → 유리함",ex:"Speed is his advantage.",exKo:"속도가 그의 장점이다."},
      {w:"affect",pron:"/əˈfekt/",pos:"v",mean:"영향을 미치다",struct:"af-(~에) + fect(만들다, 하다) → ~에 작용하다",ex:"Stress affects health.",exKo:"스트레스는 건강에 영향을 미친다."},
      {w:"aggressive",pron:"/əˈɡresɪv/",pos:"adj",mean:"공격적인, 적극적인",struct:"ag-(~로) + gress(가다) + -ive → 마구 나아가는",ex:"He played in an aggressive way.",exKo:"그는 공격적으로 경기했다."},

      {w:"alarm",pron:"/əˈlɑːrm/",pos:"n/v",mean:"경보; 놀라게 하다",struct:"이탈리아어 all'arme(무기를 들어라!) → 경보",ex:"The fire alarm rang loudly.",exKo:"화재경보가 크게 울렸다."},
      {w:"alter",pron:"/ˈɔːltər/",pos:"v",mean:"바꾸다, 변경하다",struct:"alter(=other 다른) → 다르게 만들다",ex:"Don't alter the original plan.",exKo:"원래 계획을 바꾸지 마라."},
      {w:"amount",pron:"/əˈmaʊnt/",pos:"n",mean:"양, 액수",struct:"a-(~로) + mount(오르다) → 합쳐 오른 것 → 총량",ex:"A large amount of money.",exKo:"많은 양의 돈."},
      {w:"analyze",pron:"/ˈænəlaɪz/",pos:"v",mean:"분석하다",struct:"ana-(완전히) + lyze(풀다) → 완전히 풀어헤치다",ex:"Let's analyze the data.",exKo:"데이터를 분석해 보자."},
      {w:"ancient",pron:"/ˈeɪnʃənt/",pos:"adj",mean:"고대의, 아주 오래된",struct:"anci(앞선, 이전) + -ent → 오래전의",ex:"ancient Egypt and its pyramids",exKo:"고대 이집트와 그 피라미드"},
      {w:"announce",pron:"/əˈnaʊns/",pos:"v",mean:"발표하다, 알리다",struct:"an-(~에게) + nounce(전하다) → 알려 전하다",ex:"They announced the result.",exKo:"그들은 결과를 발표했다."},
      {w:"anticipate",pron:"/ænˈtɪsɪpeɪt/",pos:"v",mean:"예상하다, 기대하다",struct:"anti-(미리) + cip(잡다) + -ate → 미리 잡다",ex:"We anticipate good weather.",exKo:"우리는 좋은 날씨를 예상한다."},
      {w:"anxious",pron:"/ˈæŋkʃəs/",pos:"adj",mean:"불안한, 갈망하는",struct:"ang(조이다, 답답) + -ious → 마음이 죄이는",ex:"She felt anxious before the test.",exKo:"그녀는 시험 전에 불안했다."},
      {w:"apparent",pron:"/əˈpærənt/",pos:"adj",mean:"분명한, 겉보기의",struct:"ap-(~에) + par(보이다) + -ent → 드러나 보이는",ex:"It was apparent that he lied.",exKo:"그가 거짓말한 게 분명했다."},
      {w:"appeal",pron:"/əˈpiːl/",pos:"v/n",mean:"호소하다, 매력",struct:"ap-(~로) + peal(몰다) → 마음을 ~로 몰다",ex:"The ad appeals to teens.",exKo:"그 광고는 십대에게 호소한다."},

      {w:"appreciate",pron:"/əˈpriːʃieɪt/",pos:"v",mean:"감사하다, 진가를 알다",struct:"ap-(~에) + preci(가치) + -ate → 가치를 매기다",ex:"I appreciate your help.",exKo:"당신의 도움에 감사합니다."},
      {w:"approach",pron:"/əˈproʊtʃ/",pos:"v/n",mean:"다가가다; 접근법",struct:"ap-(~로) + proach(=near 가까이) → 가까이 가다",ex:"Winter is approaching.",exKo:"겨울이 다가오고 있다."},
      {w:"appropriate",pron:"/əˈproʊpriət/",pos:"adj",mean:"적절한",struct:"ap-(~에) + propri(자기의) + -ate → 딱 맞는",ex:"Wear appropriate clothes.",exKo:"적절한 옷을 입어라."},
      {w:"approve",pron:"/əˈpruːv/",pos:"v",mean:"승인하다, 찬성하다",struct:"ap-(~에) + prove(좋다고 증명) → 좋다고 인정",ex:"The board approved the plan.",exKo:"이사회가 그 계획을 승인했다."},
      {w:"argue",pron:"/ˈɑːrɡjuː/",pos:"v",mean:"논쟁하다, 주장하다",struct:"argu(밝히다, 분명히) → 따져 밝히다",ex:"They argue about money.",exKo:"그들은 돈 때문에 다툰다."},
      {w:"arrange",pron:"/əˈreɪndʒ/",pos:"v",mean:"정리하다, 마련하다",struct:"ar-(~로) + range(줄 세우다) → 줄지어 놓다",ex:"Arrange the books by size.",exKo:"책을 크기별로 정리해라."},
      {w:"assist",pron:"/əˈsɪst/",pos:"v",mean:"돕다",struct:"as-(곁에) + sist(서다) → 곁에 서서 돕다",ex:"Nurses assist doctors.",exKo:"간호사는 의사를 돕는다."},
      {w:"associate",pron:"/əˈsoʊsieɪt/",pos:"v",mean:"연관 짓다, 어울리다",struct:"as-(~에) + soci(동료) + -ate → 동료로 묶다",ex:"I associate summer with the sea.",exKo:"나는 여름 하면 바다가 떠오른다."},
      {w:"assume",pron:"/əˈsuːm/",pos:"v",mean:"추정하다, 떠맡다",struct:"as-(~로) + sume(취하다) → 취해서 여기다",ex:"I assume you are right.",exKo:"나는 네가 옳다고 추정한다."},
      {w:"attach",pron:"/əˈtætʃ/",pos:"v",mean:"붙이다, 첨부하다",struct:"at-(~에) + tach(말뚝, 고정) → ~에 고정",ex:"Attach the file to the email.",exKo:"이메일에 파일을 첨부해라."},

      {w:"attempt",pron:"/əˈtempt/",pos:"v/n",mean:"시도(하다)",struct:"at-(~로) + tempt(시험하다) → 해 보려 하다",ex:"He made an attempt to win.",exKo:"그는 이기려는 시도를 했다."},
      {w:"attitude",pron:"/ˈætɪtuːd/",pos:"n",mean:"태도",struct:"apt(맞춤, 자세) → 마음의 자세",ex:"Keep a positive attitude.",exKo:"긍정적인 태도를 유지해라."},
      {w:"attract",pron:"/əˈtrækt/",pos:"v",mean:"끌어당기다, 매혹하다",struct:"at-(~로) + tract(끌다) → ~로 끌어당기다",ex:"Magnets attract iron.",exKo:"자석은 철을 끌어당긴다."},
      {w:"available",pron:"/əˈveɪləbl/",pos:"adj",mean:"이용 가능한",struct:"avail(쓸모 있다) + -able(할 수 있는)",ex:"Tickets are still available.",exKo:"표가 아직 구매 가능하다."},
      {w:"avoid",pron:"/əˈvɔɪd/",pos:"v",mean:"피하다",struct:"a-(밖으로) + void(비우다) → 비워 두다 → 멀리하다",ex:"Avoid junk food.",exKo:"정크푸드를 피해라."},
      {w:"aware",pron:"/əˈwer/",pos:"adj",mean:"알고 있는, 인식하는",struct:"a-(강조) + ware(=wary 주의하는)",ex:"Be aware of the danger.",exKo:"위험을 인식해라."},
      {w:"balance",pron:"/ˈbæləns/",pos:"n/v",mean:"균형(을 잡다)",struct:"bi-(둘) + lanc(접시) → 두 접시(저울) → 균형",ex:"Keep your balance on the bike.",exKo:"자전거에서 균형을 잡아라."},
      {w:"barrier",pron:"/ˈbæriər/",pos:"n",mean:"장벽, 장애물",struct:"bar(막대, 막다) + -ier → 막는 것",ex:"Language is no barrier to him.",exKo:"언어는 그에게 장벽이 아니다."},
      {w:"behave",pron:"/bɪˈheɪv/",pos:"v",mean:"행동하다, 처신하다",struct:"be-(강조) + have(가지다, 지니다) → 자신을 지니다",ex:"Please behave in class.",exKo:"수업 시간에 바르게 행동해라."},
      {w:"benefit",pron:"/ˈbenɪfɪt/",pos:"n/v",mean:"이익, 혜택",struct:"bene-(좋은) + fit(=fact 행함) → 좋은 일",ex:"Exercise has many benefits.",exKo:"운동은 이점이 많다."},

      {w:"brief",pron:"/briːf/",pos:"adj",mean:"간단한, 짧은",struct:"brev(짧은) → 짧은",ex:"Keep your answer brief.",exKo:"답을 간단히 해라."},
      {w:"calculate",pron:"/ˈkælkjuleɪt/",pos:"v",mean:"계산하다",struct:"calcul(작은 돌, 셈돌) + -ate → 돌로 셈하다",ex:"Calculate the total cost.",exKo:"총비용을 계산해라."},
      {w:"capable",pron:"/ˈkeɪpəbl/",pos:"adj",mean:"유능한, 할 수 있는",struct:"cap(잡다, 담다) + -able → 담아낼 수 있는",ex:"She is capable of great work.",exKo:"그녀는 훌륭한 일을 해낼 수 있다."},
      {w:"capture",pron:"/ˈkæptʃər/",pos:"v",mean:"붙잡다, 포착하다",struct:"capt(잡다) + -ure → 붙잡음",ex:"The photo captured the moment.",exKo:"그 사진은 순간을 포착했다."},
      {w:"cause",pron:"/kɔːz/",pos:"n/v",mean:"원인; 일으키다",struct:"caus(이유, 원인) → 원인",ex:"Smoking can cause disease.",exKo:"흡연은 병을 일으킬 수 있다."},
      {w:"cautious",pron:"/ˈkɔːʃəs/",pos:"adj",mean:"조심스러운",struct:"caut(조심) + -ious → 조심하는",ex:"Be cautious on icy roads.",exKo:"빙판길에서 조심해라."},
      {w:"cease",pron:"/siːs/",pos:"v",mean:"그치다, 멈추다",struct:"cess/ceas(가다, 물러나다) → 물러나 멈추다",ex:"The rain ceased at noon.",exKo:"비가 정오에 그쳤다."},
      {w:"challenge",pron:"/ˈtʃælɪndʒ/",pos:"n/v",mean:"도전(하다)",struct:"calumn(헐뜯다→겨루다) → 겨룸 → 도전",ex:"Climbing is a real challenge.",exKo:"등반은 진정한 도전이다."},
      {w:"circumstance",pron:"/ˈsɜːrkəmstæns/",pos:"n",mean:"상황, 환경",struct:"circum-(둘레) + stance(서다) → 둘러선 형편",ex:"under difficult circumstances",exKo:"어려운 상황 속에서"},
      {w:"claim",pron:"/kleɪm/",pos:"v/n",mean:"주장하다; 주장",struct:"clam(외치다) → 큰소리로 주장",ex:"He claims he is innocent.",exKo:"그는 자신이 결백하다고 주장한다."},

      {w:"collapse",pron:"/kəˈlæps/",pos:"v/n",mean:"무너지다; 붕괴",struct:"col-(함께) + lapse(미끄러지다) → 함께 무너지다",ex:"The old bridge collapsed.",exKo:"낡은 다리가 무너졌다."},
      {w:"combine",pron:"/kəmˈbaɪn/",pos:"v",mean:"결합하다",struct:"com-(함께) + bine(둘씩) → 둘을 함께",ex:"Combine flour and sugar.",exKo:"밀가루와 설탕을 섞어라."},
      {w:"comment",pron:"/ˈkɑːment/",pos:"n/v",mean:"논평(하다), 댓글",struct:"com-(함께) + ment(생각) → 곁들인 말",ex:"He left a kind comment.",exKo:"그는 친절한 댓글을 남겼다."},
      {w:"commit",pron:"/kəˈmɪt/",pos:"v",mean:"저지르다, 전념하다",struct:"com-(함께) + mit(보내다) → 맡기다/저지르다",ex:"Commit to your goal.",exKo:"목표에 전념해라."},
      {w:"compare",pron:"/kəmˈper/",pos:"v",mean:"비교하다",struct:"com-(함께) + par(같은) → 나란히 견주다",ex:"Compare the two photos.",exKo:"두 사진을 비교해라."},
      {w:"compete",pron:"/kəmˈpiːt/",pos:"v",mean:"경쟁하다",struct:"com-(함께) + pete(추구하다) → 함께 겨루다",ex:"Teams compete for the cup.",exKo:"팀들이 우승컵을 두고 경쟁한다."},
      {w:"complex",pron:"/kəmˈpleks/",pos:"adj",mean:"복잡한",struct:"com-(함께) + plex(엮다) → 얽혀 있는",ex:"a complex problem",exKo:"복잡한 문제"},
      {w:"concentrate",pron:"/ˈkɑːnsəntreɪt/",pos:"v",mean:"집중하다",struct:"con-(함께) + centr(중심) + -ate → 중심으로 모으다",ex:"Concentrate on your work.",exKo:"일에 집중해라."},
      {w:"concept",pron:"/ˈkɑːnsept/",pos:"n",mean:"개념",struct:"con-(함께) + cept(잡다) → 머릿속에 잡은 것",ex:"a difficult concept",exKo:"어려운 개념"},
      {w:"conclude",pron:"/kənˈkluːd/",pos:"v",mean:"결론짓다, 끝맺다",struct:"con-(완전히) + clude(닫다) → 완전히 닫다",ex:"She concluded her speech.",exKo:"그녀는 연설을 끝맺었다."},

      {w:"conduct",pron:"/kənˈdʌkt/",pos:"v/n",mean:"수행하다; 행동",struct:"con-(함께) + duct(이끌다) → 이끌어 가다",ex:"They conducted a survey.",exKo:"그들은 설문을 실시했다."},
      {w:"confident",pron:"/ˈkɑːnfɪdənt/",pos:"adj",mean:"자신 있는",struct:"con-(완전히) + fid(믿다) + -ent → 굳게 믿는",ex:"She is confident of winning.",exKo:"그녀는 이길 자신이 있다."},
      {w:"confirm",pron:"/kənˈfɜːrm/",pos:"v",mean:"확인하다, 확정하다",struct:"con-(완전히) + firm(굳은) → 굳히다",ex:"Please confirm your booking.",exKo:"예약을 확인해 주세요."},
      {w:"conflict",pron:"/ˈkɑːnflɪkt/",pos:"n/v",mean:"갈등; 충돌하다",struct:"con-(함께) + flict(치다) → 서로 부딪치다",ex:"a conflict between friends",exKo:"친구 사이의 갈등"},
      {w:"confuse",pron:"/kənˈfjuːz/",pos:"v",mean:"혼란시키다",struct:"con-(함께) + fuse(붓다) → 뒤섞다",ex:"The map confused me.",exKo:"그 지도가 나를 혼란시켰다."},
      {w:"consider",pron:"/kənˈsɪdər/",pos:"v",mean:"고려하다, 여기다",struct:"con-(함께) + sider(별을 보다) → 곰곰이 살피다",ex:"Consider all options.",exKo:"모든 선택지를 고려해라."},
      {w:"consist",pron:"/kənˈsɪst/",pos:"v",mean:"구성되다, 이루어지다",struct:"con-(함께) + sist(서다) → 함께 서 있다",ex:"Water consists of H and O.",exKo:"물은 수소와 산소로 이루어진다."},
      {w:"constant",pron:"/ˈkɑːnstənt/",pos:"adj",mean:"끊임없는, 일정한",struct:"con-(함께) + stant(서다) → 변함없이 서 있는",ex:"constant noise from the road",exKo:"도로에서 나는 끊임없는 소음"},
      {w:"construct",pron:"/kənˈstrʌkt/",pos:"v",mean:"건설하다, 구성하다",struct:"con-(함께) + struct(쌓다) → 쌓아 올리다",ex:"They construct bridges.",exKo:"그들은 다리를 건설한다."},
      {w:"consume",pron:"/kənˈsuːm/",pos:"v",mean:"소비하다",struct:"con-(완전히) + sume(취하다) → 다 써버리다",ex:"Cars consume fuel.",exKo:"차는 연료를 소비한다."},

      {w:"contain",pron:"/kənˈteɪn/",pos:"v",mean:"담고 있다, 포함하다",struct:"con-(함께) + tain(잡다) → 안에 잡아 두다",ex:"This box contains toys.",exKo:"이 상자는 장난감을 담고 있다."},
      {w:"context",pron:"/ˈkɑːntekst/",pos:"n",mean:"맥락, 문맥",struct:"con-(함께) + text(짜다) → 함께 짜인 글",ex:"Guess the word from context.",exKo:"문맥으로 단어를 추측해라."},
      {w:"continue",pron:"/kənˈtɪnjuː/",pos:"v",mean:"계속하다",struct:"con-(함께) + tin(잡다) → 계속 잡고 있다",ex:"Continue reading the book.",exKo:"그 책을 계속 읽어라."},
      {w:"contribute",pron:"/kənˈtrɪbjuːt/",pos:"v",mean:"기여하다, 기부하다",struct:"con-(함께) + tribute(주다) → 함께 보태다",ex:"Everyone contributed ideas.",exKo:"모두가 아이디어를 보탰다."},
      {w:"convince",pron:"/kənˈvɪns/",pos:"v",mean:"설득하다, 확신시키다",struct:"con-(완전히) + vince(이기다) → 완전히 이겨 믿게 하다",ex:"He convinced me to join.",exKo:"그는 내가 합류하도록 설득했다."},
      {w:"cooperate",pron:"/koʊˈɑːpəreɪt/",pos:"v",mean:"협력하다",struct:"co-(함께) + operate(일하다) → 함께 일하다",ex:"We must cooperate to win.",exKo:"이기려면 협력해야 한다."},
      {w:"create",pron:"/kriˈeɪt/",pos:"v",mean:"창조하다, 만들다",struct:"creat(낳다, 자라게 하다) → 만들어 내다",ex:"Artists create beauty.",exKo:"예술가는 아름다움을 창조한다."},
      {w:"criticize",pron:"/ˈkrɪtɪsaɪz/",pos:"v",mean:"비판하다",struct:"critic(판단하는) + -ize → 판단하여 따지다",ex:"Don't criticize too harshly.",exKo:"너무 심하게 비판하지 마라."},
      {w:"crucial",pron:"/ˈkruːʃəl/",pos:"adj",mean:"결정적인, 중대한",struct:"cruc(십자, 갈림길) + -ial → 갈림길의 → 중요한",ex:"a crucial decision",exKo:"결정적인 결정"},
      {w:"cure",pron:"/kjʊr/",pos:"v/n",mean:"치료(하다)",struct:"cur(돌보다) → 돌봐서 낫게 하다",ex:"This will cure the cold.",exKo:"이것이 감기를 낫게 할 것이다."},

      {w:"curious",pron:"/ˈkjʊriəs/",pos:"adj",mean:"호기심 많은",struct:"cur(주의, 돌봄) + -ious → 관심 많은",ex:"Cats are curious animals.",exKo:"고양이는 호기심 많은 동물이다."},
      {w:"damage",pron:"/ˈdæmɪdʒ/",pos:"n/v",mean:"손상, 피해(를 입히다)",struct:"damn(손해) + -age → 해를 입힘",ex:"The storm caused damage.",exKo:"폭풍이 피해를 일으켰다."},
      {w:"declare",pron:"/dɪˈkler/",pos:"v",mean:"선언하다, 신고하다",struct:"de-(완전히) + clare(분명히) → 분명히 밝히다",ex:"They declared independence.",exKo:"그들은 독립을 선언했다."},
      {w:"decline",pron:"/dɪˈklaɪn/",pos:"v/n",mean:"감소(하다), 거절하다",struct:"de-(아래로) + cline(기울다) → 아래로 기울다",ex:"Sales began to decline.",exKo:"매출이 줄기 시작했다."},
      {w:"dedicate",pron:"/ˈdedɪkeɪt/",pos:"v",mean:"바치다, 헌신하다",struct:"de-(완전히) + dic(말하다, 선언) + -ate → 바치겠다 선언",ex:"She dedicated her life to art.",exKo:"그녀는 평생을 예술에 바쳤다."},
      {w:"define",pron:"/dɪˈfaɪn/",pos:"v",mean:"정의하다",struct:"de-(완전히) + fine(끝, 경계) → 경계를 짓다",ex:"Define the word clearly.",exKo:"그 단어를 분명히 정의해라."},
      {w:"delay",pron:"/dɪˈleɪ/",pos:"v/n",mean:"미루다; 지연",struct:"de-(떨어져) + lay(=lax 느슨) → 늦추다",ex:"The flight was delayed.",exKo:"비행기가 지연되었다."},
      {w:"deliver",pron:"/dɪˈlɪvər/",pos:"v",mean:"배달하다, 전하다",struct:"de-(완전히) + liver(=liberate 풀어주다) → 넘겨주다",ex:"They deliver pizza fast.",exKo:"그들은 피자를 빨리 배달한다."},
      {w:"demand",pron:"/dɪˈmænd/",pos:"v/n",mean:"요구(하다); 수요",struct:"de-(완전히) + mand(명령) → 강하게 요구",ex:"Workers demand higher pay.",exKo:"노동자들이 더 높은 임금을 요구한다."},
      {w:"demonstrate",pron:"/ˈdemənstreɪt/",pos:"v",mean:"증명하다, 시연하다",struct:"de-(완전히) + monstr(보이다) + -ate → 똑똑히 보이다",ex:"He demonstrated the trick.",exKo:"그는 그 묘기를 시연했다."},

      {w:"deny",pron:"/dɪˈnaɪ/",pos:"v",mean:"부인하다, 거부하다",struct:"de-(완전히) + ny(=no 아니다) → 아니라고 하다",ex:"He denied the rumor.",exKo:"그는 그 소문을 부인했다."},
      {w:"depend",pron:"/dɪˈpend/",pos:"v",mean:"의존하다, ~에 달려 있다",struct:"de-(아래로) + pend(매달다) → ~에 매달리다",ex:"Children depend on parents.",exKo:"아이들은 부모에게 의존한다."},
      {w:"describe",pron:"/dɪˈskraɪb/",pos:"v",mean:"묘사하다, 설명하다",struct:"de-(아래로) + scribe(쓰다) → 적어 내려가다",ex:"Describe your hometown.",exKo:"네 고향을 묘사해라."},
      {w:"desire",pron:"/dɪˈzaɪər/",pos:"n/v",mean:"욕구; 바라다",struct:"de-(완전히) + sire(별→바라다) → 간절히 바라다",ex:"a strong desire to learn",exKo:"배우려는 강한 욕구"},
      {w:"destroy",pron:"/dɪˈstrɔɪ/",pos:"v",mean:"파괴하다",struct:"de-(반대로) + stroy(쌓다) → 쌓은 것을 허물다",ex:"Fire destroyed the house.",exKo:"불이 집을 파괴했다."},
      {w:"detail",pron:"/ˈdiːteɪl/",pos:"n",mean:"세부 사항",struct:"de-(완전히) + tail(자르다) → 잘게 자른 것",ex:"Explain it in detail.",exKo:"그것을 자세히 설명해라."},
      {w:"detect",pron:"/dɪˈtekt/",pos:"v",mean:"발견하다, 감지하다",struct:"de-(반대) + tect(덮다) → 덮개를 벗기다",ex:"Dogs can detect smells.",exKo:"개는 냄새를 감지할 수 있다."},
      {w:"determine",pron:"/dɪˈtɜːrmɪn/",pos:"v",mean:"결정하다, 알아내다",struct:"de-(완전히) + termin(경계, 끝) → 끝을 정하다",ex:"Genes determine eye color.",exKo:"유전자가 눈 색깔을 결정한다."},
      {w:"develop",pron:"/dɪˈveləp/",pos:"v",mean:"발전시키다, 개발하다",struct:"de-(반대) + velop(싸다) → 포장을 풀다 → 펼치다",ex:"develop new skills",exKo:"새로운 기술을 개발하다"},
      {w:"devote",pron:"/dɪˈvoʊt/",pos:"v",mean:"바치다, 쏟다",struct:"de-(완전히) + vote(맹세) → 바치겠다 맹세",ex:"She devotes time to study.",exKo:"그녀는 공부에 시간을 쏟는다."},

      {w:"differ",pron:"/ˈdɪfər/",pos:"v",mean:"다르다",struct:"dif-(떨어져) + fer(나르다) → 따로 떨어지다",ex:"Tastes differ from person to person.",exKo:"취향은 사람마다 다르다."},
      {w:"disappear",pron:"/ˌdɪsəˈpɪr/",pos:"v",mean:"사라지다",struct:"dis-(반대) + appear(나타나다) → 안 나타나다",ex:"The sun disappeared.",exKo:"해가 사라졌다."},
      {w:"discover",pron:"/dɪˈskʌvər/",pos:"v",mean:"발견하다",struct:"dis-(반대) + cover(덮다) → 덮개를 벗기다",ex:"Columbus discovered a route.",exKo:"콜럼버스가 항로를 발견했다."},
      {w:"distance",pron:"/ˈdɪstəns/",pos:"n",mean:"거리",struct:"di-(떨어져) + stance(서다) → 떨어져 선 정도",ex:"a long distance to walk",exKo:"걸어가기엔 먼 거리"},
      {w:"distinguish",pron:"/dɪˈstɪŋɡwɪʃ/",pos:"v",mean:"구별하다",struct:"di-(떨어져) + stingu(찌르다) → 찔러 가르다",ex:"distinguish right from wrong",exKo:"옳고 그름을 구별하다"},
      {w:"distribute",pron:"/dɪˈstrɪbjuːt/",pos:"v",mean:"분배하다, 나눠 주다",struct:"dis-(따로) + tribute(주다) → 따로따로 주다",ex:"distribute the books",exKo:"책을 나눠 주다"},
      {w:"disturb",pron:"/dɪˈstɜːrb/",pos:"v",mean:"방해하다",struct:"dis-(완전히) + turb(휘젓다) → 마구 휘젓다",ex:"Don't disturb the baby.",exKo:"아기를 방해하지 마라."},
      {w:"divide",pron:"/dɪˈvaɪd/",pos:"v",mean:"나누다",struct:"di-(떨어져) + vide(쪼개다) → 갈라 쪼개다",ex:"Divide the cake into six.",exKo:"케이크를 여섯으로 나눠라."},
      {w:"dominate",pron:"/ˈdɑːmɪneɪt/",pos:"v",mean:"지배하다, 우세하다",struct:"domin(주인) + -ate → 주인 노릇 하다",ex:"One team dominated the game.",exKo:"한 팀이 경기를 지배했다."},
      {w:"doubt",pron:"/daʊt/",pos:"n/v",mean:"의심(하다)",struct:"dub(둘) → 둘 사이에서 갈팡질팡 → 의심",ex:"I have no doubt about it.",exKo:"나는 그것에 의심이 없다."},

      {w:"dramatic",pron:"/drəˈmætɪk/",pos:"adj",mean:"극적인",struct:"drama(극) + -tic → 연극 같은",ex:"a dramatic change",exKo:"극적인 변화"},
      {w:"earn",pron:"/ɜːrn/",pos:"v",mean:"(돈을) 벌다, 얻다",struct:"고대영어 earnian(노동의 대가를 받다)",ex:"She earns a good salary.",exKo:"그녀는 좋은 급여를 번다."},
      {w:"effective",pron:"/ɪˈfektɪv/",pos:"adj",mean:"효과적인",struct:"ef-(밖으로) + fect(만들다) + -ive → 결과를 내는",ex:"an effective method",exKo:"효과적인 방법"},
      {w:"efficient",pron:"/ɪˈfɪʃənt/",pos:"adj",mean:"효율적인",struct:"ef-(밖으로) + fic(만들다) + -ent → 잘 만들어 내는",ex:"an efficient engine",exKo:"효율적인 엔진"},
      {w:"elect",pron:"/ɪˈlekt/",pos:"v",mean:"선출하다",struct:"e-(밖으로) + lect(고르다) → 골라내다",ex:"They elected a leader.",exKo:"그들은 지도자를 선출했다."},
      {w:"emerge",pron:"/ɪˈmɜːrdʒ/",pos:"v",mean:"나타나다, 드러나다",struct:"e-(밖으로) + merge(잠기다) → 물 밖으로 나오다",ex:"The truth emerged later.",exKo:"진실이 나중에 드러났다."},
      {w:"emphasize",pron:"/ˈemfəsaɪz/",pos:"v",mean:"강조하다",struct:"em-(안에) + phas(보이다) + -ize → 도드라지게 하다",ex:"She emphasized safety.",exKo:"그녀는 안전을 강조했다."},
      {w:"enable",pron:"/ɪˈneɪbl/",pos:"v",mean:"가능하게 하다",struct:"en-(~하게 만들다) + able(할 수 있는)",ex:"The app enables fast search.",exKo:"그 앱은 빠른 검색을 가능하게 한다."},
      {w:"encourage",pron:"/ɪnˈkɜːrɪdʒ/",pos:"v",mean:"격려하다",struct:"en-(~하게) + courage(용기) → 용기를 주다",ex:"Teachers encourage students.",exKo:"교사는 학생을 격려한다."},
      {w:"enormous",pron:"/ɪˈnɔːrməs/",pos:"adj",mean:"거대한",struct:"e-(밖으로) + norm(기준) → 기준을 벗어난 → 엄청난",ex:"an enormous building",exKo:"거대한 건물"},

      {w:"ensure",pron:"/ɪnˈʃʊr/",pos:"v",mean:"보장하다, 확실히 하다",struct:"en-(~하게) + sure(확실한) → 확실하게 하다",ex:"Ensure the door is locked.",exKo:"문이 잠겼는지 확실히 해라."},
      {w:"entire",pron:"/ɪnˈtaɪər/",pos:"adj",mean:"전체의",struct:"en-(부정 아님) + tire(=integer 온전한) → 온전한",ex:"the entire class",exKo:"반 전체"},
      {w:"environment",pron:"/ɪnˈvaɪrənmənt/",pos:"n",mean:"환경",struct:"en-(둘레) + viron(돌다) + -ment → 둘러싼 것",ex:"protect the environment",exKo:"환경을 보호하다"},
      {w:"equal",pron:"/ˈiːkwəl/",pos:"adj",mean:"동등한",struct:"equ(같은) + -al → 같은",ex:"Cut it into equal parts.",exKo:"그것을 똑같은 조각으로 잘라라."},
      {w:"escape",pron:"/ɪˈskeɪp/",pos:"v/n",mean:"탈출(하다)",struct:"es-(밖으로) + cape(망토) → 망토를 벗어 던지듯 빠져나가다",ex:"They escaped the fire.",exKo:"그들은 화재에서 탈출했다."},
      {w:"essential",pron:"/ɪˈsenʃəl/",pos:"adj",mean:"필수적인",struct:"ess(존재하다) + -ial → 존재의 핵심인",ex:"Water is essential to life.",exKo:"물은 생명에 필수적이다."},
      {w:"establish",pron:"/ɪˈstæblɪʃ/",pos:"v",mean:"설립하다, 확립하다",struct:"e-(강조) + stabl(굳건한) → 굳건히 세우다",ex:"establish a company",exKo:"회사를 설립하다"},
      {w:"estimate",pron:"/ˈestɪmeɪt/",pos:"v/n",mean:"추정(하다)",struct:"estim(값을 매기다) + -ate → 값을 가늠하다",ex:"Estimate the cost first.",exKo:"먼저 비용을 추정해라."},
      {w:"evidence",pron:"/ˈevɪdəns/",pos:"n",mean:"증거",struct:"e-(밖으로) + vid(보다) + -ence → 눈에 드러난 것",ex:"There is no evidence yet.",exKo:"아직 증거가 없다."},
      {w:"evolve",pron:"/ɪˈvɑːlv/",pos:"v",mean:"진화하다, 발전하다",struct:"e-(밖으로) + volve(굴리다) → 굴려 펼쳐지다",ex:"Species evolve over time.",exKo:"종은 시간이 지나며 진화한다."},

      {w:"exact",pron:"/ɪɡˈzækt/",pos:"adj",mean:"정확한",struct:"ex-(밖으로) + act(몰다) → 딱 맞게 몰아낸",ex:"the exact time",exKo:"정확한 시간"},
      {w:"examine",pron:"/ɪɡˈzæmɪn/",pos:"v",mean:"조사하다, 검사하다",struct:"exam(저울로 달다) + -ine → 꼼꼼히 재다",ex:"The doctor examined me.",exKo:"의사가 나를 진찰했다."},
      {w:"exchange",pron:"/ɪksˈtʃeɪndʒ/",pos:"v/n",mean:"교환(하다)",struct:"ex-(밖으로) + change(바꾸다) → 서로 바꾸다",ex:"exchange gifts",exKo:"선물을 교환하다"},
      {w:"exist",pron:"/ɪɡˈzɪst/",pos:"v",mean:"존재하다",struct:"ex-(밖으로) + ist(서다) → 밖에 나와 서 있다",ex:"Do ghosts exist?",exKo:"유령이 존재할까?"},
      {w:"expand",pron:"/ɪkˈspænd/",pos:"v",mean:"확장하다, 팽창하다",struct:"ex-(밖으로) + pand(펴다) → 밖으로 펴다",ex:"The company expanded fast.",exKo:"그 회사는 빠르게 확장했다."},
      {w:"expect",pron:"/ɪkˈspekt/",pos:"v",mean:"기대하다, 예상하다",struct:"ex-(밖을) + spect(보다) → 내다보다",ex:"I expect good news.",exKo:"나는 좋은 소식을 기대한다."},
      {w:"experience",pron:"/ɪkˈspɪriəns/",pos:"n/v",mean:"경험(하다)",struct:"ex-(밖으로) + peri(시도) → 겪어 본 것",ex:"a great experience",exKo:"멋진 경험"},
      {w:"explain",pron:"/ɪkˈspleɪn/",pos:"v",mean:"설명하다",struct:"ex-(밖으로) + plain(평평한) → 평평히 펴 보이다",ex:"Explain the rule again.",exKo:"규칙을 다시 설명해라."},
      {w:"explore",pron:"/ɪkˈsplɔːr/",pos:"v",mean:"탐험하다, 탐구하다",struct:"ex-(밖으로) + plore(외치다) → 찾아 나서다",ex:"They explored the cave.",exKo:"그들은 동굴을 탐험했다."},
      {w:"express",pron:"/ɪkˈspres/",pos:"v",mean:"표현하다",struct:"ex-(밖으로) + press(누르다) → 밖으로 짜내다",ex:"Express your feelings.",exKo:"네 감정을 표현해라."},

      {w:"extend",pron:"/ɪkˈstend/",pos:"v",mean:"연장하다, 확장하다",struct:"ex-(밖으로) + tend(뻗다) → 밖으로 뻗다",ex:"extend the deadline",exKo:"마감을 연장하다"},
      {w:"extreme",pron:"/ɪkˈstriːm/",pos:"adj",mean:"극단적인",struct:"extrem(가장 바깥) → 끝에 있는",ex:"extreme weather",exKo:"극단적인 날씨"},
      {w:"familiar",pron:"/fəˈmɪliər/",pos:"adj",mean:"익숙한, 친숙한",struct:"famil(가족) + -iar → 가족처럼 친한",ex:"a familiar face",exKo:"익숙한 얼굴"},
      {w:"favor",pron:"/ˈfeɪvər/",pos:"n/v",mean:"호의, 부탁",struct:"fav(잘해 주다) → 잘 봐줌",ex:"Do me a favor.",exKo:"부탁 하나 들어줘."},
      {w:"focus",pron:"/ˈfoʊkəs/",pos:"v/n",mean:"집중(하다); 초점",struct:"라틴어 focus(화로, 중심) → 한 점에 모음",ex:"Focus on the goal.",exKo:"목표에 집중해라."},
      {w:"forbid",pron:"/fərˈbɪd/",pos:"v",mean:"금지하다",struct:"for-(반대) + bid(명령) → 하지 말라 명하다",ex:"The sign forbids parking.",exKo:"그 표지판은 주차를 금지한다."},
      {w:"forecast",pron:"/ˈfɔːrkæst/",pos:"n/v",mean:"예보(하다)",struct:"fore-(미리) + cast(던지다) → 미리 던져 보다",ex:"the weather forecast",exKo:"일기 예보"},
      {w:"former",pron:"/ˈfɔːrmər/",pos:"adj",mean:"이전의, 전자의",struct:"fore(앞) + -mer → 앞선",ex:"the former president",exKo:"전 대통령"},
      {w:"fortune",pron:"/ˈfɔːrtʃən/",pos:"n",mean:"행운, 재산",struct:"fortun(운) → 운, 한밑천",ex:"good fortune",exKo:"행운"},
      {w:"frequent",pron:"/ˈfriːkwənt/",pos:"adj",mean:"잦은",struct:"frequ(가득 찬) + -ent → 빈번한",ex:"frequent visits",exKo:"잦은 방문"},

      {w:"frustrate",pron:"/ˈfrʌstreɪt/",pos:"v",mean:"좌절시키다",struct:"frustra(헛되이) + -ate → 헛수고로 만들다",ex:"The delay frustrated us.",exKo:"그 지연이 우리를 좌절시켰다."},
      {w:"function",pron:"/ˈfʌŋkʃən/",pos:"n/v",mean:"기능(하다)",struct:"funct(수행하다) + -ion → 하는 일",ex:"the function of the heart",exKo:"심장의 기능"},
      {w:"fundamental",pron:"/ˌfʌndəˈmentl/",pos:"adj",mean:"근본적인",struct:"fund(바닥, 기초) + -mental → 기초가 되는",ex:"a fundamental rule",exKo:"근본적인 규칙"},
      {w:"generate",pron:"/ˈdʒenəreɪt/",pos:"v",mean:"발생시키다, 만들어 내다",struct:"gener(낳다) + -ate → 만들어 내다",ex:"Wind generates power.",exKo:"바람이 전력을 만든다."},
      {w:"genuine",pron:"/ˈdʒenjuɪn/",pos:"adj",mean:"진짜의, 진실한",struct:"genu(타고난) + -ine → 타고난 그대로의",ex:"a genuine smile",exKo:"진실한 미소"},
      {w:"grateful",pron:"/ˈɡreɪtfl/",pos:"adj",mean:"고마워하는",struct:"grat(기쁜, 감사) + -ful → 감사로 가득한",ex:"I'm grateful for your help.",exKo:"도움에 감사드립니다."},
      {w:"guarantee",pron:"/ˌɡærənˈtiː/",pos:"v/n",mean:"보장(하다)",struct:"warrant(보증)에서 유래 → 책임지고 보증",ex:"We guarantee quality.",exKo:"우리는 품질을 보장한다."},
      {w:"hesitate",pron:"/ˈhezɪteɪt/",pos:"v",mean:"망설이다",struct:"haes(달라붙다) + -itate → 발이 붙어 머뭇거리다",ex:"Don't hesitate to ask.",exKo:"주저 말고 물어봐라."},
      {w:"identify",pron:"/aɪˈdentɪfaɪ/",pos:"v",mean:"확인하다, 식별하다",struct:"ident(같은) + -ify → 같은 것임을 밝히다",ex:"identify the problem",exKo:"문제를 파악하다"},
      {w:"ignore",pron:"/ɪɡˈnɔːr/",pos:"v",mean:"무시하다",struct:"i-(아닌) + gnore(알다) → 모른 척하다",ex:"Don't ignore the warning.",exKo:"경고를 무시하지 마라."},

      {w:"imitate",pron:"/ˈɪmɪteɪt/",pos:"v",mean:"모방하다",struct:"imit(닮다) + -ate → 흉내 내다",ex:"Parrots imitate sounds.",exKo:"앵무새는 소리를 흉내 낸다."},
      {w:"immediate",pron:"/ɪˈmiːdiət/",pos:"adj",mean:"즉각적인",struct:"im-(없는) + medi(중간) → 사이가 없는 → 곧바로",ex:"an immediate reply",exKo:"즉각적인 답변"},
      {w:"impact",pron:"/ˈɪmpækt/",pos:"n",mean:"영향, 충격",struct:"im-(안으로) + pact(치다) → 안으로 부딪침",ex:"a big impact on society",exKo:"사회에 미치는 큰 영향"},
      {w:"imply",pron:"/ɪmˈplaɪ/",pos:"v",mean:"암시하다",struct:"im-(안에) + ply(접다) → 안에 접어 두다 → 함축",ex:"Silence may imply consent.",exKo:"침묵은 동의를 암시할 수 있다."},
      {w:"impress",pron:"/ɪmˈpres/",pos:"v",mean:"감명을 주다",struct:"im-(안으로) + press(누르다) → 마음에 새기다",ex:"Her speech impressed me.",exKo:"그녀의 연설이 내게 감명을 주었다."},
      {w:"improve",pron:"/ɪmˈpruːv/",pos:"v",mean:"향상시키다",struct:"im-(~로) + prove(이익) → 더 좋게 만들다",ex:"Improve your English daily.",exKo:"매일 영어를 향상시켜라."},
      {w:"include",pron:"/ɪnˈkluːd/",pos:"v",mean:"포함하다",struct:"in-(안에) + clude(닫다) → 안에 가두다",ex:"The price includes tax.",exKo:"가격은 세금을 포함한다."},
      {w:"increase",pron:"/ɪnˈkriːs/",pos:"v/n",mean:"증가(하다)",struct:"in-(안으로) + crease(자라다) → 점점 자라다",ex:"Prices increase yearly.",exKo:"가격이 매년 오른다."},
      {w:"indicate",pron:"/ˈɪndɪkeɪt/",pos:"v",mean:"나타내다, 가리키다",struct:"in-(~로) + dic(말하다) + -ate → 가리켜 보이다",ex:"The sign indicates danger.",exKo:"그 표지는 위험을 나타낸다."},
      {w:"individual",pron:"/ˌɪndɪˈvɪdʒuəl/",pos:"n/adj",mean:"개인(의)",struct:"in-(아닌) + divid(나누다) → 더 못 나누는 → 개체",ex:"each individual student",exKo:"각각의 학생"},

      {w:"influence",pron:"/ˈɪnfluəns/",pos:"n/v",mean:"영향(을 주다)",struct:"in-(안으로) + flu(흐르다) → 안으로 흘러듦",ex:"media influence on teens",exKo:"십대에 대한 매체의 영향"},
      {w:"inform",pron:"/ɪnˈfɔːrm/",pos:"v",mean:"알리다",struct:"in-(안에) + form(형태) → 마음에 형태를 넣어 주다",ex:"Inform me of the change.",exKo:"변경 사항을 알려 줘."},
      {w:"injure",pron:"/ˈɪndʒər/",pos:"v",mean:"부상을 입히다",struct:"in-(부정) + jure(법, 옳음) → 옳지 않게 하다 → 해치다",ex:"He injured his knee.",exKo:"그는 무릎을 다쳤다."},
      {w:"innocent",pron:"/ˈɪnəsənt/",pos:"adj",mean:"무죄의, 순진한",struct:"in-(아닌) + noc(해치다) + -ent → 해치지 않은",ex:"an innocent child",exKo:"순진한 아이"},
      {w:"inspire",pron:"/ɪnˈspaɪər/",pos:"v",mean:"영감을 주다",struct:"in-(안으로) + spire(숨쉬다) → 숨을 불어넣다",ex:"Her story inspired me.",exKo:"그녀의 이야기가 내게 영감을 주었다."},
      {w:"instant",pron:"/ˈɪnstənt/",pos:"adj",mean:"즉각적인",struct:"in-(~에) + stant(서다) → 그 순간에 선",ex:"instant noodles",exKo:"즉석 면(라면)"},
      {w:"intend",pron:"/ɪnˈtend/",pos:"v",mean:"의도하다",struct:"in-(~로) + tend(뻗다) → 마음을 ~로 뻗다",ex:"I intend to study abroad.",exKo:"나는 유학할 작정이다."},
      {w:"interpret",pron:"/ɪnˈtɜːrprɪt/",pos:"v",mean:"해석하다, 통역하다",struct:"inter-(사이) + pret(거래) → 사이를 풀어 주다",ex:"interpret a poem",exKo:"시를 해석하다"},
      {w:"invest",pron:"/ɪnˈvest/",pos:"v",mean:"투자하다",struct:"in-(안에) + vest(옷 입히다) → 자본을 입히다",ex:"invest in education",exKo:"교육에 투자하다"},
      {w:"involve",pron:"/ɪnˈvɑːlv/",pos:"v",mean:"포함하다, 관련시키다",struct:"in-(안으로) + volve(굴리다) → 안으로 말아 넣다",ex:"The job involves travel.",exKo:"그 일은 출장을 포함한다."},

      {w:"isolate",pron:"/ˈaɪsəleɪt/",pos:"v",mean:"고립시키다, 분리하다",struct:"isol(섬) + -ate → 섬처럼 떼어 놓다",ex:"isolate the sick birds",exKo:"아픈 새들을 격리하다"},
      {w:"judge",pron:"/dʒʌdʒ/",pos:"v/n",mean:"판단하다; 판사",struct:"jud(법) + dic(말하다) → 법으로 말하다",ex:"Don't judge by looks.",exKo:"겉모습으로 판단하지 마라."},
      {w:"justify",pron:"/ˈdʒʌstɪfaɪ/",pos:"v",mean:"정당화하다",struct:"just(올바른) + -ify → 옳게 만들다",ex:"Nothing can justify lying.",exKo:"어떤 것도 거짓말을 정당화할 수 없다."},
      {w:"labor",pron:"/ˈleɪbər/",pos:"n",mean:"노동",struct:"labor(수고, 일) → 힘든 일",ex:"manual labor",exKo:"육체노동"},
      {w:"lack",pron:"/læk/",pos:"n/v",mean:"부족(하다)",struct:"중세영어 lac(모자람)",ex:"a lack of sleep",exKo:"수면 부족"},
      {w:"maintain",pron:"/meɪnˈteɪn/",pos:"v",mean:"유지하다",struct:"main(손) + tain(잡다) → 손에 쥐고 있다",ex:"maintain good health",exKo:"건강을 유지하다"},
      {w:"major",pron:"/ˈmeɪdʒər/",pos:"adj",mean:"주요한, 큰",struct:"maj(큰) + -or → 더 큰",ex:"a major problem",exKo:"주요한 문제"},
      {w:"manage",pron:"/ˈmænɪdʒ/",pos:"v",mean:"관리하다, 해내다",struct:"man(손) + -age → 손으로 다루다",ex:"manage a team",exKo:"팀을 관리하다"},
      {w:"mature",pron:"/məˈtʃʊr/",pos:"adj/v",mean:"성숙한; 성숙하다",struct:"matur(익은) → 무르익은",ex:"a mature attitude",exKo:"성숙한 태도"},
      {w:"measure",pron:"/ˈmeʒər/",pos:"v/n",mean:"측정하다; 조치",struct:"mens(재다) → 길이를 재다",ex:"measure the length",exKo:"길이를 재다"},
    ]
  }
  // 다음 작업: LEVELS.S2 = { code:"S2", label:"...", perDay:10, words:[ ... ] }
};

/* 자주 나오는 어근·접두사 (참고 패널) */
const ROOTS = [
  ["ad- / ac- / ap-", "~로, ~에 (방향)", "accept, approach, attract"],
  ["com- / con-", "함께, 완전히", "combine, conclude, connect"],
  ["de-", "아래로, 분리, 완전히", "decline, define, destroy"],
  ["dis- / di-", "반대, 분리", "disappear, divide, distinct"],
  ["ex- / e-", "밖으로", "expand, emerge, escape"],
  ["in- / im-", "안으로 / 부정(아닌)", "include, import / innocent"],
  ["pro-", "앞으로", "produce, progress, project"],
  ["re-", "다시, 뒤로", "return, reduce, reflect"],
  ["-able / -ible", "~할 수 있는", "capable, available"],
  ["-ate / -ify / -ize", "~하게 만들다 (동사)", "create, justify, emphasize"],
  ["spect / spec", "보다", "expect, respect, inspect"],
  ["tract", "끌다", "attract, abstract, extract"],
  ["mit / miss", "보내다", "admit, submit, mission"],
  ["port", "나르다", "export, import, transport"],
];

const ACTIVE_LEVEL = "S1";
function getLevel(code){ return LEVELS[code || ACTIVE_LEVEL]; }
function getWords(code){ return getLevel(code).words; }
function getPerDay(code){ return getLevel(code).perDay || 10; }
function getDayCount(code){ return Math.ceil(getWords(code).length / getPerDay(code)); }
/* day: 1-based. 해당 Day의 단어 인덱스 배열 반환 */
function getDayIndices(day, code){
  const per = getPerDay(code), n = getWords(code).length;
  const start = (day-1)*per;
  const out = [];
  for(let i=start; i<Math.min(start+per, n); i++) out.push(i);
  return out;
}
